apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: huge-tarantula-nodejs
  janus-idp.io/tekton: huge-tarantula-nodejs
  backstage.io/kubernetes-id: huge-tarantula-nodejs
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: huge-tarantula-nodejs
resources: 
- deployment.yaml
- route.yaml
- service.yaml
