apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: huge-tarantula-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: huge-tarantula-nodejs 
  name: huge-tarantula-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: huge-tarantula-nodejs 
